### ISSUE TITLE
Targets(Labels) do need??

### ISSUE THREAD

**Issue by edwardcho** [Cory-M/DCCM#12]
Hello Sir,

For Clustering, I think that the target(label) needs not for clustering.
But I saw targets(labels) on your code.

Targets(Labels) do need on training for your code??

Thanks,
Edward Cho.

**Comment by Cory-M** [comment]
no we don't need ground truth target for training. For "targets" at https://github.com/Cory-M/DCCM/blob/master/main.py#L176-L178 they are all pseudo targets generated by the similarity matrix, you can check https://github.com/Cory-M/DCCM/blob/master/main.py#L165 for details.

**Comment by edwardcho** [comment]
Hello Sir,

But I still have some questions.
Please see at https://github.com/Cory-M/DCCM/blob/master/main.py#L148.
you can see target of inputs.

Thanks,
Edward Cho.

**Comment by Cory-M** [comment]
yes but they are not used
