### ISSUE TITLE
Unhandled last batch truncation

### ISSUE THREAD

**Issue by willi-menapace** [Cory-M/DCCM#2]
It seems that line `145` in `main.py` is the cause for an index out of range in subsequent lines when training on the last batch of a dataset that has size non divisible by `large_bs`.

Correcting the line as follows should fix the issue
`#index_loc = np.arange(args.large_bs)`
`# We use the actual batch size instead of the parameter to avoid errors on truncated batches`
`index_loc = np.arange(input_tensor.size()[0])`

**Comment by Cory-M** [comment]
Thanks for pointing out - I think that makes sense. Another option is to set "drop_last = True" in Dataloader.
