### ISSUE TITLE
ValueError: NumpyArrayIterator is set to use the data format convention "channels_last"

### ISSUE THREAD

**Issue by HellFireC02** [Cory-M/DCCM#3]
Excuse me, i have a question that cant solve for a long time.

I want to use your code to deal with clustering task by using NUS-WIDE dataset.
I organize these images on your suggestion in 'data' folder and put nus_lable.txt in 'meta' folder.
Then i add 'resize' operation in your 'mc_dataset.py'
It's just about:
1.from skimage.transform import resize
2.img = resize(img, (32, 32))     ------before  30 line

Besides, I just modified cifar10.yaml for:
small_bs: 16
workers: 4
num_classes: 4

Other than the above, I didn't modify any other files.(Except some notes I wrote)

But when i run 'main_2.py' using 'python main_2.py --config cfgs/cifar10.yaml'
(main_2.py is just a copy of main.py and added with my note)
It shows:
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "main_2.py", line 309, in <module>
    main()
  File "main_2.py", line 140, in main
    train(dataloader, model, dim_loss, crit_label, crit_graph, crit_c, optimizer, epoch, datagen, tb_logger)
  File "main_2.py", line 203, in train
    for X_batch_i in datagen.flow(input_bs,batch_size=args.small_bs,shuffle=False):
  File "/home/sky/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py", line 460, in flow
    save_format=save_format)
  File "/home/sky/anaconda2/lib/python2.7/site-packages/keras/preprocessing/image.py", line 782, in __init__
    ' (' + str(self.x.shape[channels_axis]) + ' channels).')
ValueError: NumpyArrayIterator is set to use the data format convention "channels_last" (channels on axis 3), i.e. expected either 1, 3 or 4 channels on axis 3. However, it was passed an array with shape (16, 3, 32, 32) (32 channels).
-------------------------------------------------------------------------------
I dont know how to solve this problem.
Is something wrong for my modification?
Or your main.py has something need to revise?
I would appreciate it if you could help me solve this problem!

**Comment by Cory-M** [comment]
Hi, sorry for the late reply. You could change the  "image_data_format" from **channels_last** to **channels_first** in you Keras configuration file. (usually, it's at $HOME/.keras/keras.json) I think that would help to solve the issue.
Let me know if bugs still exist.

**Comment by HellFireC02** [comment]
> Hi, sorry for the late reply. You could change the "image_data_format" from **channels_last** to **channels_first** in you Keras configuration file. (usually, it's at $HOME/.keras/keras.json) I think that would help to solve the issue.
> Let me know if bugs still exist.

thanks for your reply, but this leads to another error...
it shows:
---------------------------------------------------
Traceback (most recent call last):
  File "main_2.py", line 309, in <module>
    main()
  File "main_2.py", line 140, in main
    train(dataloader, model, dim_loss, crit_label, crit_graph, crit_c, optimizer, epoch, datagen, tb_logger)
  File "main_2.py", line 188, in train
    input_bs = input_tensor[address]
RuntimeError: index 921 is out of bounds for dim with size 855
---------------------------------------------------
I think the reason for this error is the setting of 'address', or the 'large_bs' and the 'small_bs'.
specifically,i set:
---------------------------------------------------
large_bs: 1000
small_bs: 16
repeated: 10
input_size: 32
workers: 4
num_classes: 4
---------------------------------------------------
so i wonder that something wrong in my above setting.
should i change large_bs or num_classes?
looking forward to your reply!

**Comment by Cory-M** [comment]
you could simply add "drop_last=True" in torch.utils.data.DataLoader at line 92 in the original main.py : ) also refer to the other closed issue at https://github.com/Cory-M/DCCM/issues/2 is necessary.

**Comment by HellFireC02** [comment]
thanks for your kindly help
there's no any error during running period!
