### ISSUE TITLE
How to use other model(eg. vgg16) to run your code?

### ISSUE THREAD

**Issue by HellFireC02** [Cory-M/DCCM#5]
I want to use a model with more layers (eg. vgg) to deal with problems in my field, but your code only provides the cifar_c4_L2 model. If I want to customize my own model, what modifications should I make?

I noticed that there are **layers, c_layer and classifier** in the cifar10.yaml file. Is this related to calculating the mutual information between the shallow and deep layers?
And how should this value be modified in the custom model?

**Comment by Cory-M** [comment]
hi, referring to cifar_c4_L2 model, you can customize yours into the "features" and "fc_layer" blocks; layers is a list [shallow layer, deep layer] (for example [2, 10] means computing the mutual information between the 2rd and 10th layer) , c_layer is an int, means the layer we use to evaluate classification accuracy. classifier is the classifier we would like to use. 
basically you can look through utils/functions.py to see what's happening in "forward" and customize your own model.
hope that helps

**Comment by HellFireC02** [comment]
thanks for your explanation, i will try to modify function.py file to see how it works.
