### ISSUE TITLE
other architectures and config files

### ISSUE THREAD

**Issue by kartikgupta-at-anu** [Cory-M/DCCM#7]
can you please upload other architectures and the config yml files for other datasets such as STL10, and TinyImageNet?

Also, in the supplementary you mention avg pool is used with stride 2 for cifar10/100 but in the code you use stride 4? Which one is correct?

**Comment by Cory-M** [comment]
hi, since both me and @Jlwu1992 have left SenseTime and don't have the access to our repo anymore, it might take us a while to find them and publish them. We are working on that. Sorry!

Yes, the code with stride=4 is correct. it was a typo in the supplementary.
